# Generated by Django 3.2.10 on 2022-03-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchList', '0002_alter_review_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='rating_number',
            field=models.IntegerField(default=0),
        ),
    ]
